/* eslint-disable @next/next/no-img-element */
import { BigLogo } from "@/components/app-component/biglogo";
import { SideBar } from "@/components/app-component/sidebar/Sidebar";
import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
  icons: "/icons/main-logo.svg",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen w-full flex relative">
      {/* Side bar */}
      <SideBar />
      <section className="w-full p-5">{children}</section>
    </main>
  );
}
